name: OTA Deploy to AWS
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "Build version with SHA"

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      ALLOWED_TEST: ${{ startsWith(github.ref, 'refs/heads/test-release/') }}
      ALLOWED_PROD: ${{ startsWith(github.ref, 'refs/heads/release/') && contains('congyue-chewie:kelly-chewie:jthomp-chewie', github.actor) }}
    steps:
      - id: step1
        run: echo "::set-output name=output1::`echo ${GITHUB_SHA} | cut -c1-8`"