name: output-demo-2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.contents.outputs.data }}
      output2: ${{ steps.number1.outputs.num1 }}
      output3: ${{ steps.number2.outputs.num2 }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run python script
        id: contents
        run: |
          python create_txt_file.py
          contents=$( cat readme.txt )
          echo "::set-output name=data::$contents"

      - id: number1
        run: echo "::set-output name=num1::'123'"

      - id: number2
        run: echo "::set-output name=num2::'456'"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} 

      - name: sum up
        run: |
          sum1=$((${{needs.job1.outputs.output2}} + ${{needs.job1.outputs.output3}}))
          echo $sum1
          echo ${{needs.job1.outputs.output2}}
          echo ${{needs.job1.outputs.output3}}


