name: Overwrite some file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: checking
        run: |
          pwd
          ls -l
          echo "guo12345" >> guo1.txt
          ls -l

      - name: Set Random Number
        id: set_random_num
        run: |
          randomNumA=$RANDOM
          randomNumB=$RANDOM
          echo "randomNumA: $randomNumA"
          echo "random_numA=$randomNumA" >> $GITHUB_ENV
          echo "randomNumB: $randomNumB"
          echo "random_numB=$randomNumB" >> $GITHUB_ENV

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: guo1.txt
          write-mode: overwrite
          contents: |
            fileA:${{ env.random_numA}}  fileb:${{ env.random_numB}}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'