name: Upload Debug Symbols
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "Build version with SHA"

jobs:
  upload_symbols:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2